nodeLinker: hoisted

packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: ^4.3.6
  typescript: ^5.9.3
  "@types/node": 24.10.4
  "@libsql/client": ^0.17.0

catalogs:
  tailwind:
    "@tailwindcss/vite": ^4.1.18
    tailwindcss: ^4.1.18
    tailwind-merge: ^3.4.0
    tw-animate-css: ^1.4.0
  vitest:
    vitest: ^4.0.18
    "@vitest/browser-playwright": ^4.0.18
    vitest-browser-react: ^2.0.5
  react:
    react: ^19.2.4
    react-dom: ^19.2.4
    "@types/react": ^19.2.11
    "@types/react-dom": ^19.2.3
  tanstack:
    "@tanstack/react-form": ^1.28.0
    "@tanstack/react-query": ^5.90.20
    "@tanstack/react-router": ^1.158.0
    "@tanstack/react-router-devtools": ^1.158.0
    "@tanstack/router-plugin": ^1.158.0
    "@tanstack/react-devtools": ^0.9.4
    "@tanstack/query-db-collection": ^1.0.22
    "@tanstack/react-db": ^0.1.69
  better-auth:
    better-auth: ^1.4.18
    "@better-auth/cli": ^1.4.18
  cloudflare:
    "@cloudflare/workers-types": ^4.20260203.0
    wrangler: ^4.62.0
  drizzle:
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
    drizzle-zod: ^0.8.3
  orpc:
    "@orpc/client": ^1.13.4
    "@orpc/contract": ^1.13.4
    "@orpc/openapi": ^1.13.4
    "@orpc/openapi-client": ^1.13.4
    "@orpc/server": ^1.13.4
    "@orpc/tanstack-query": ^1.13.4
  effect:
    "effect": ^3.19.16
    "@effect/platform": ^0.94.3
    "@effect/rpc": ^0.73.0
    "@effect/sql": ^0.49.0
    "@effect/sql-d1": ^0.47.0
    "@effect/sql-drizzle": ^0.48.0
    "@effect/language-service": ^0.73.0
