packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: ^4.3.6
  typescript: ^5.9.3
  "@types/node": 24.10.4
  "@libsql/client": ^0.17.0

catalogs:
  tailwind:
    "@tailwindcss/vite": ^4.1.18
    tailwindcss: ^4.1.18
    tailwind-merge: ^3.4.0
    tw-animate-css: ^1.4.0
  vitest:
    vitest: ^4.0.18
    "@vitest/browser-playwright": ^4.0.18
    vitest-browser-react: ^2.0.4
  react:
    react: ^19.2.3
    react-dom: ^19.2.3
    "@types/react": ^19.2.9
    "@types/react-dom": ^19.2.3
  tanstack:
    "@tanstack/react-form": ^1.27.7
    "@tanstack/react-query": ^5.90.20
    "@tanstack/react-router": ^1.157.14
    "@tanstack/react-router-devtools": ^1.157.14
    "@tanstack/router-plugin": ^1.157.14
    "@tanstack/react-devtools": ^0.9.2
    "@tanstack/query-db-collection": ^1.0.20
    "@tanstack/react-db": ^0.1.67
  better-auth:
    better-auth: ^1.4.17
    "@better-auth/cli": ^1.4.17
  cloudflare:
    "@cloudflare/workers-types": ^4.20260124.0
    wrangler: ^4.60.0
  drizzle:
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
    drizzle-zod: ^0.8.3
  orpc:
    "@orpc/client": ^1.13.4
    "@orpc/contract": ^1.13.4
    "@orpc/openapi": ^1.13.4
    "@orpc/openapi-client": ^1.13.4
    "@orpc/server": ^1.13.4
    "@orpc/tanstack-query": ^1.13.4
